apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qpfk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qpfk
    app.kubernetes.io/part-of: ci1t-830-0097-app
  name: devfile-sample-qpfk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qpfk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qpfk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0097-tenant/ci1t-830-0097-app/devfile-sample-qpfk@sha256:e7f32d384b0781218ba59f79481ce0a70fc786354ddab01b3a266d7ed847e947
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
